/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "isr_uart_rx.h"
#include "PWM_M1.h"
#include "Clock_PWM.h"
#include "Pin_PWM1_aliases.h"
#include "Pin_PWM1.h"
#include "isr_1.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "ADC_SAR_V.h"
#include "Pin_PWM2_aliases.h"
#include "Pin_PWM2.h"
#include "PWM_M2.h"
#include "PWM_M3.h"
#include "Pin_ADC_V_aliases.h"
#include "Pin_ADC_V.h"
#include "Pin_PWM3_aliases.h"
#include "Pin_PWM3.h"
#include "PWM_M4.h"
#include "Pin_PWM4_aliases.h"
#include "Pin_PWM4.h"
#include "SPI_Slave.h"
#include "SPI_Slave_PVT.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "SS_aliases.h"
#include "SS.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "ISR_SPI.h"
#include "ADC_SAR_B.h"
#include "Pin_ADC_B_aliases.h"
#include "Pin_ADC_B.h"
#include "PWM_P.h"
#include "Clock_PWM_4.h"
#include "Pin_PWM_P_aliases.h"
#include "Pin_PWM_P.h"
#include "LEDB_aliases.h"
#include "LEDB.h"
#include "LEDV_aliases.h"
#include "LEDV.h"
#include "UART_1_IntClock.h"
#include "ADC_SAR_V_IRQ.h"
#include "ADC_SAR_V_theACLK.h"
#include "ADC_SAR_V_ExtVref_aliases.h"
#include "ADC_SAR_V_ExtVref.h"
#include "SPI_Slave_IntClock.h"
#include "ADC_SAR_B_IRQ.h"
#include "ADC_SAR_B_theACLK.h"
#include "ADC_SAR_B_ExtVref_aliases.h"
#include "ADC_SAR_B_ExtVref.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

